### ISSUE TITLE
Custom Layout Button

### ISSUE THREAD

**Issue by amirisback** [amirisback/frogo-notification#4]
### Discussed in https://github.com/amirisback/frogo-notification/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **amirisback** January 14, 2021</sup>

Possible to add a button to the notification ? That's the only thing I am missing. Thnaks for this amazing library by 
@supersu-man

</div>

**Comment by amirisback** [comment]
https://gist.github.com/codinginflow/cdccf55feb4516c9f630d70fdceb4cea this is the answer, but i will try for inject into this library

**Comment by supersu-man** [comment]
Amazing. Waiting for the new release 😁.

**Comment by amirisback** [comment]
don't worry, while you wait, you can try all my libraries in my repository.  https://github.com/amirisback/awesome-project-catalogue @supersu-man

**Comment by amirisback** [comment]
you can download / using version 1.0.6 thank you
